FROM centos:7
MAINTAINER Norbert Bondarczuk (norbertx.bondarczuk@intel.com)
RUN yum -y update
RUN yum install -y iperf3 git perl bcc bcc-devel bcc-tools devtoolset-10-perftools perf sudo elfutils-libelf-devel libunwind-devel audit-libs-devel slang-devel
WORKDIR /work
RUN git clone https://github.com/brendangregg/FlameGraph
ENV PATH=/bin:/usr/sbin:/usr/bin:/usr/share/bcc/tools:/work:/work/FlameGraph
ADD make-flamegraph.sh /work
HEALTHCHECK CMD exit 0
ENTRYPOINT sleep inf

